### ISSUE TITLE
power-assert を正しく動かす

### ISSUE THREAD

**Issue by kjirou** [kjirou/express-nested-router#2]
### 以下の表示になってしまう

```
AssertionError: [1,2,3] deepEqual [1,2,3,4]
at Decorator.concreteAssert (/Users/kjirou/app/express-nested-router/node_modules/power-assert/node_modules/empower/lib/decorator.j
```
### ある程度は改善した
- Node.js のバージョンを `0.11.11` から `0.10.22` へ変更
- 関連ライブラリのバージョンを https://github.com/azu/power-assert-node-seed で使われているものに固定（こっちは無関係かも、未確認）

```
  "devDependencies": {
    "espower-loader": "^0.8.0",
    "intelli-espower-loader": "^0.3.0",
    "power-assert": "^0.8.0"
  }
```
### それでも、まだこんな感じ

![](http://i.gyazo.com/3a5c5c4e4a5009b933c42c810196f8d3.png)
- インデントがおかしい
- 色が単色（シェルの設定？）

**Comment by twada** [comment]
power-assert をお使い頂きありがとうございます。

現状の出力ですが、
- インデント幅を設けていないので、コンソール左に張り付いた出力になってしまいます
- 色に関しては、 power-assert は mocha のアサーションメッセージを組み立てて渡すだけなので、 mocha の失敗色である赤単色になっています。

(バージョンは 0.9.0 でも同じ出力になると思います)

よいフィードバックを頂いたので、上記の点を今後改善します。

**Comment by kjirou** [comment]
アドバイスありがとうございます！
では、設定はおかしくないんすね。

ちょっと補足させていただくと：

> インデントがおかしい
> 色が単色（シェルの設定？）

こちらは機能が不足しているから困る、という意味よりも、
本来の出力とは違う（っぽい）ので現状設定ミスかもしれない、直そう、という意味でした。

私見ですが、インデントに関しては、幅が広く取れる今の方が便利な可能性もあると思っています。

**Comment by kjirou** [comment]
### Todo
- 色付けを mocha 側で頑張ってみる（後回しでいいや）
- 関連ライブラリのバージョン再調整

**Comment by twada** [comment]
> 私見ですが、インデントに関しては、幅が広く取れる今の方が便利な可能性もあると思っています。

なるほどなるほど。ありがとうございます!

**Comment by kjirou** [comment]
Fixed by https://github.com/kjirou/express-nested-router/commit/dcc1ddb319d055418aa8c130706da7853bf1078d
